-- Insert all menu items
INSERT INTO menu_items (id, name, description, price, image, category_id, sub_category, calories, volume, ingredients, available, quantity, rating) VALUES
-- MAINS - SOUP (7 items)
('main-soup-1', 'Hungarian Soup', 'Traditional Hungarian soup with beef, vegetables and aromatic spices', 350, 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg?auto=compress&cs=tinysrgb&w=600', 'noodles', 'soup', 320, '350ml', ARRAY['Beef', 'Carrot', 'Cabbage', 'Zikuni', 'French Beans', 'Garlic', 'Chili', 'Ginger', 'Salt', 'Oil'], true, 12, 4.8),
('main-soup-2', 'Carrot Soup', 'Creamy carrot soup with fresh vegetables', 300, 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600', 'noodles', 'soup', 280, '300ml', ARRAY['Carrot', 'Onion', 'Celery', 'Leek', 'Green Beans', 'Salt', 'Oil'], true, 8, 4.6),
('main-soup-3', 'Tomato Soup', 'Classic tomato soup with fresh herbs', 280, 'https://images.pexels.com/photos/1640776/pexels-photo-1640776.jpeg?auto=compress&cs=tinysrgb&w=600', 'noodles', 'soup', 250, '350ml', ARRAY['Tomato', 'Onion', 'Garlic', 'Basil', 'Salt', 'Oil'], true, 10, 4.5),
('main-soup-4', 'Pumpkin Soup', 'Smooth and creamy pumpkin soup', 250, 'https://images.pexels.com/photos/1640775/pexels-photo-1640775.jpeg?auto=compress&cs=tinysrgb&w=600', 'noodles', 'soup', 220, '350ml', ARRAY['Pumpkin', 'Onion', 'Celery', 'Leek', 'Salt', 'Oil'], true, 15, 4.7),
('main-soup-5', 'Minestrone Soup', 'Italian vegetable soup with pasta', 400, 'https://images.pexels.com/photos/2703468/pexels-photo-2703468.jpeg?auto=compress&cs=tinysrgb&w=600', 'noodles', 'soup', 350, '400ml', ARRAY['Carrot', 'Onion', 'French Beans', 'Celery', 'Garlic', 'Cream', 'Zikuni', 'Leek', 'Salt', 'Oil'], true, 10, 4.6),
('main-soup-6', 'Chicken Cream Soup', 'Rich and creamy chicken soup', 500, 'https://images.pexels.com/photos/539451/pexels-photo-539451.jpeg?auto=compress&cs=tinysrgb&w=600', 'noodles', 'soup', 420, '400ml', ARRAY['Chicken', 'Butter', 'Flour', 'Cream', 'Oil', 'Salt', 'Sweet Pepper'], true, 8, 4.9),
('main-soup-7', 'Vegetable Soup', 'Healthy mixed vegetable soup', 250, 'https://images.pexels.com/photos/1731535/pexels-photo-1731535.jpeg?auto=compress&cs=tinysrgb&w=600', 'noodles', 'soup', 200, '350ml', ARRAY['Carrot', 'French Beans', 'Leek', 'Onion', 'Zikuni', 'Celery', 'Potato', 'Sweet Pepper', 'Salt', 'Oil'], true, 12, 4.5);
